apiVersion: v1
kind: ConfigMap
metadata:
  name: api-pipelinetest-config
  namespace: ext
data:
  APP_ID: "9gtmLwcG7/dotuw1/kFHIG9BkKGXGYKB+8Wm23eDHadBlAtgORWjN4PGl157mIwvTupu7U4EvnqCDta+Rgcp7w=="
  ENV: "ext"
  ENV_KIBANA: "ext"
  ENVIRONMENT: "EXT"
  REDIS_URL: "redis-ext.pismolabs.io:6379"
  SQS_AUTHORIZATIONS_QUEUE: "https://sqs.sa-east-1.amazonaws.com/270036487593/Authorizations-qa"
  MYSQL_URL: "jdbc:mysql://db-pismolabs-qa.pismolabs.io:3306/pismolabs?autoReconnect=true"
  SYSTEM: "p2pTransactions"
  RULES_API_URL: "https://api-rules-ext.pismolabs.io"
  BANKACCOUNTS_SEC_URL: "https://sec-bankaccounts-ext.pismolabs.io"
  METRICS_HOST : "http://a5134e9b29d3311e7ab63023576355bf-1808260220.sa-east-1.elb.amazonaws.com:9411/api/v1/spans/"
  LOGSTASH_URL: "logstash.pismolabs.io:80"
